### ISSUE TITLE
Search displays correct results momentarily then displays every application

### ISSUE THREAD

**Issue by wski** [ozone-development/center-ui#71] opened 2015-02-20 16:02 UTC
Search displays correct results momentarily then displays every application.

To reproduce: 

Search 'air',
Wait a few seconds.
Air Mail will pop up followed by every singe application it seems.

**Comment by rpokorny** [comment] 2015-02-20 16:08
Interestingly it seems if you backspace to just 'ai' after this happens it will search correctly.  Then if you type the 'r' again it stays correct.

**Comment by rpokorny** [comment] 2015-02-20 16:11
Also adding a space after the word 'air' will break it again

**Comment by mparizernc** [comment] 2015-02-20 18:19
Adding a space makes sense and having them all show makes sense. We add a * after every string, so adding a space means you would be searching air<sp>*. Which means it is going to search for air or * since it is not in quotes.

**Comment by rpokorny** [comment] 2015-02-20 18:27
I understand that, but I hardly consider it to be correct from a usability perspective

**Comment by mparizernc** [comment] 2015-02-20 18:48
Well because of how the stemming works unless you type the correct word exactly you won't find it for example if you type a or ai you will not find listings only if you type air.

Also I am unable to reproduce this issue locally on this appears to be a front end issue because the service is only returning the one listing.

**Comment by rpokorny** [comment] 2015-02-20 20:26
It appears to be processing the search results out of order.  The "all" that is showing up is technically all listings that match the search "a" (which is probably in fact all of them).  I am fixing that, trimming whitespace before wildcards are applied (to fix the trailing space issue) and also adding a 500ms debounce

**Comment by rpokorny** [comment] 2015-02-20 20:29
I have also found an issue where it will display all listings if the last search term is quoted.  I will fix that as well

**Comment by rpokorny** [comment] 2015-02-20 20:33
Resolved in abf3007

**Comment by mparizernc** [comment] 2015-03-02 18:35
Verified that the search pauses until the user stops typing.  Verified the searching of strings using double quotes and without quotes.

**Closed** 2015-03-05 15:36 UTC
Labels: 5 - Done, bug-IOB
