### ISSUE TITLE
Make HTML Title tag configurable "AppsMall Center"

### ISSUE THREAD

**Issue by tonyalletag** [ozone-development/center-ui#91] opened 2015-02-26 15:41 UTC
Production users are seeing incorrect title in there tabs, This also is showing up in metrics as OZONE Marketplace instead of AppsMall Center

title - Needs to be configurable - title

**Comment by sdeighan** [comment] 2015-02-26 15:57
Unfortunately, this is not really a bug.

We can't update this here on Github unless we are changing our FOSS release branding to all "AppsMall". In order for us to do anything, we'd need to make this a configurable as a feature and it will add a substantial amount of development time.

**Comment by rpokorny** [comment] 2015-02-26 16:01
I think @tonyalletag is saying that it should be a configuration setting, just like the different configurable URLs we have in center-ui.  The default could still be something FOSS-friendly.  Assuming that is the case I don't see anything preventing that from being possible.

**Comment by mparizernc** [comment] 2015-02-26 16:01
So are you looking to just change the tab name or everywhere that Marketplace is found?

**Comment by sdeighan** [comment] 2015-02-26 16:03
I agree that, in order to achieve this, making the platform configurable is the right course. However, the name "OZONE Marketplace" isn't a mistake and, to do this right, it would be adding a feature. Yes? @rpokorny

**Comment by rpokorny** [comment] 2015-02-26 16:04
Yeah I think that would be an "Improvement" in our old JIRA parlance, not a bug

**Comment by tonyalletag** [comment] 2015-02-26 18:32
Agree this is not a bug but we would like it to be configurable.

**Comment by mparizernc** [comment] 2015-02-26 18:42
Tony, confirmed this ticket is just for the browser tab.  It is possible that we may need to make it configurable for the system but we will tackle that when/if arises.

**Comment by rpokorny** [comment] 2015-02-26 22:33
This is now done both here and in HUD.  The new configuration is called APP_TITLE

**Comment by mparizernc** [comment] 2015-02-27 13:40
@rpokorny This works in IE and Chrome but not in Firefox.

**Comment by nishp1** [comment] 2015-02-27 14:08
I added a comment to the commit last night, not sure if you guys were notified or not, but `document.title` should be used to get and set title of the tab/window.

**Comment by rpokorny** [comment] 2015-02-27 14:09
Yeah I got notified of that.  Trying it now. It fixed it in Firefox so I'm just testing the other browsers to make sure.

**Comment by rpokorny** [comment] 2015-02-27 14:53
Firefox issue fixed via Nish's suggestion

**Comment by mparizernc** [comment] 2015-02-27 16:11
All Browsers
Verified that the the tab name changes for both the HUD and Center based on the configuration.

**Closed** 2015-03-05 15:37 UTC
Labels: 5 - Done, enhancement
